#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterIniciativaData
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MaterIniciativa")]
	public partial class DataMaterDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataMaterDataContext() : 
				base(global::MaterIniciativaData.Properties.Settings.Default.MaterIniciativaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataMaterDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataMaterDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataMaterDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataMaterDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DepartmentGet")]
		public ISingleResult<DepartmentGetResult> DepartmentGet([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdDepartment", DbType="Int")] System.Nullable<int> idDepartment)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idDepartment);
			return ((ISingleResult<DepartmentGetResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UserUpdate")]
		public int UserUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUser", DbType="Int")] System.Nullable<int> idUser, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="VarChar(250)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(250)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(250)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Active", DbType="Int")] System.Nullable<int> active, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AppMember", DbType="Int")] System.Nullable<int> appMember, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(250)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Surname", DbType="VarChar(250)")] string surname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="InsertedId", DbType="Int")] ref System.Nullable<int> insertedId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUser, userName, password, email, active, appMember, name, surname, insertedId);
			insertedId = ((System.Nullable<int>)(result.GetParameterValue(8)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DepartmentList")]
		public ISingleResult<DepartmentListResult> DepartmentList()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<DepartmentListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DepartmentPlantList")]
		public ISingleResult<DepartmentPlantListResult> DepartmentPlantList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPlant", DbType="Int")] System.Nullable<int> idPlant)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPlant);
			return ((ISingleResult<DepartmentPlantListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EcoregionGet")]
		public ISingleResult<EcoregionGetResult> EcoregionGet([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEcoregion", DbType="Int")] System.Nullable<int> idEcoregion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEcoregion);
			return ((ISingleResult<EcoregionGetResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EcoregionList")]
		public ISingleResult<EcoregionListResult> EcoregionList()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<EcoregionListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EcoRegionPlantList")]
		public ISingleResult<EcoRegionPlantListResult> EcoRegionPlantList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPlant", DbType="Int")] System.Nullable<int> idPlant)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPlant);
			return ((ISingleResult<EcoRegionPlantListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PhotoGet")]
		public ISingleResult<PhotoGetResult> PhotoGet([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPhoto", DbType="Int")] System.Nullable<int> idPhoto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPhoto);
			return ((ISingleResult<PhotoGetResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PhotoList")]
		public ISingleResult<PhotoListResult> PhotoList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPlant", DbType="Int")] System.Nullable<int> idPlant)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPlant);
			return ((ISingleResult<PhotoListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PhotoUpdate")]
		public int PhotoUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPhoto", DbType="Int")] System.Nullable<int> idPhoto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPlant", DbType="Int")] System.Nullable<int> idPlant, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Type", DbType="VarChar(250)")] string type, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(250)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Data", DbType="VarBinary(MAX)")] System.Data.Linq.Binary data, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Path", DbType="VarChar(250)")] string path, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="InsertedId", DbType="Int")] ref System.Nullable<int> insertedId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPhoto, idPlant, type, name, data, path, insertedId);
			insertedId = ((System.Nullable<int>)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PlantDepartmentList")]
		public ISingleResult<PlantDepartmentListResult> PlantDepartmentList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdDepartment", DbType="Int")] System.Nullable<int> idDepartment)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idDepartment);
			return ((ISingleResult<PlantDepartmentListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PlantDepartmentUpdate")]
		public int PlantDepartmentUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdDepartment", DbType="Int")] System.Nullable<int> idDepartment, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPlant", DbType="Int")] System.Nullable<int> idPlant)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idDepartment, idPlant);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PlantEcoRegionList")]
		public ISingleResult<PlantEcoRegionListResult> PlantEcoRegionList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEcoRegion", DbType="Int")] System.Nullable<int> idEcoRegion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEcoRegion);
			return ((ISingleResult<PlantEcoRegionListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PlantEcoRegionUpdate")]
		public int PlantEcoRegionUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEcoRegion", DbType="Int")] System.Nullable<int> idEcoRegion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPlant", DbType="Int")] System.Nullable<int> idPlant)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEcoRegion, idPlant);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PlantList")]
		public ISingleResult<PlantListResult> PlantList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUser", DbType="Int")] System.Nullable<int> idUser, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CommunName", DbType="VarChar(250)")] string communName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUser, communName);
			return ((ISingleResult<PlantListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PlantUpdate")]
		public int PlantUpdate(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPlant", DbType="Int")] System.Nullable<int> idPlant, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUser", DbType="Int")] System.Nullable<int> idUser, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="Int")] System.Nullable<int> status, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CountSearchs", DbType="Int")] System.Nullable<int> countSearchs, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CommonName", DbType="VarChar(250)")] string commonName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ScientificName", DbType="VarChar(250)")] string scientificName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Family", DbType="VarChar(250)")] string family, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Characteristics", DbType="VarChar(250)")] string characteristics, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Distributions", DbType="VarChar(250)")] string distributions, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Uses", DbType="VarChar(250)")] string uses, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreationDate", DbType="Date")] System.Nullable<System.DateTime> creationDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UptoDate", DbType="Date")] System.Nullable<System.DateTime> uptoDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Type", DbType="VarChar(250)")] string type, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Morphology", DbType="VarChar(250)")] string morphology, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Color", DbType="VarChar(250)")] string color, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="InsertedId", DbType="Int")] ref System.Nullable<int> insertedId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPlant, idUser, status, countSearchs, commonName, scientificName, family, characteristics, distributions, uses, creationDate, uptoDate, type, morphology, color, insertedId);
			insertedId = ((System.Nullable<int>)(result.GetParameterValue(15)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UserFavoriteList")]
		public ISingleResult<UserFavoriteListResult> UserFavoriteList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUser", DbType="Int")] System.Nullable<int> idUser)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUser);
			return ((ISingleResult<UserFavoriteListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UserFavoriteUpdate")]
		public int UserFavoriteUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUser", DbType="Int")] System.Nullable<int> idUser, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPlant", DbType="Int")] System.Nullable<int> idPlant)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUser, idPlant);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UserGet")]
		public ISingleResult<UserGetResult> UserGet([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="VarChar(250)")] string userName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName);
			return ((ISingleResult<UserGetResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PlantGet")]
		public ISingleResult<PlantGetResult> PlantGet([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPlant", DbType="Int")] System.Nullable<int> idPlant, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CommonName", DbType="VarChar(1)")] string commonName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPlant, commonName);
			return ((ISingleResult<PlantGetResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PlantUserList")]
		public ISingleResult<PlantUserListResult> PlantUserList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUser", DbType="Int")] System.Nullable<int> idUser)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUser);
			return ((ISingleResult<PlantUserListResult>)(result.ReturnValue));
		}
	}
	
	public partial class DepartmentGetResult
	{
		
		private int _IdDepartment;
		
		private string _Name;
		
		private string _Description;
		
		private System.Data.Linq.Binary _Image;
		
		private string _IimagePath;
		
		public DepartmentGetResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDepartment", DbType="Int NOT NULL")]
		public int IdDepartment
		{
			get
			{
				return this._IdDepartment;
			}
			set
			{
				if ((this._IdDepartment != value))
				{
					this._IdDepartment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(250)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this._Image = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IimagePath", DbType="VarChar(150)")]
		public string IimagePath
		{
			get
			{
				return this._IimagePath;
			}
			set
			{
				if ((this._IimagePath != value))
				{
					this._IimagePath = value;
				}
			}
		}
	}
	
	public partial class DepartmentListResult
	{
		
		private int _IdDepartment;
		
		private string _Name;
		
		private string _Description;
		
		private System.Data.Linq.Binary _Image;
		
		private string _IimagePath;
		
		public DepartmentListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDepartment", DbType="Int NOT NULL")]
		public int IdDepartment
		{
			get
			{
				return this._IdDepartment;
			}
			set
			{
				if ((this._IdDepartment != value))
				{
					this._IdDepartment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(250)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this._Image = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IimagePath", DbType="VarChar(150)")]
		public string IimagePath
		{
			get
			{
				return this._IimagePath;
			}
			set
			{
				if ((this._IimagePath != value))
				{
					this._IimagePath = value;
				}
			}
		}
	}
	
	public partial class DepartmentPlantListResult
	{
		
		private int _IdDepartment;
		
		private string _Name;
		
		private string _Description;
		
		private System.Data.Linq.Binary _Image;
		
		private string _IimagePath;
		
		public DepartmentPlantListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDepartment", DbType="Int NOT NULL")]
		public int IdDepartment
		{
			get
			{
				return this._IdDepartment;
			}
			set
			{
				if ((this._IdDepartment != value))
				{
					this._IdDepartment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(250)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this._Image = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IimagePath", DbType="VarChar(150)")]
		public string IimagePath
		{
			get
			{
				return this._IimagePath;
			}
			set
			{
				if ((this._IimagePath != value))
				{
					this._IimagePath = value;
				}
			}
		}
	}
	
	public partial class EcoregionGetResult
	{
		
		private int _IdEcoregion;
		
		private string _Name;
		
		private string _Description;
		
		private System.Data.Linq.Binary _Image;
		
		private string _ImagePath;
		
		public EcoregionGetResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEcoregion", DbType="Int NOT NULL")]
		public int IdEcoregion
		{
			get
			{
				return this._IdEcoregion;
			}
			set
			{
				if ((this._IdEcoregion != value))
				{
					this._IdEcoregion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(50)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this._Image = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImagePath", DbType="VarChar(150)")]
		public string ImagePath
		{
			get
			{
				return this._ImagePath;
			}
			set
			{
				if ((this._ImagePath != value))
				{
					this._ImagePath = value;
				}
			}
		}
	}
	
	public partial class EcoregionListResult
	{
		
		private int _IdEcoregion;
		
		private string _Name;
		
		private string _Description;
		
		private System.Data.Linq.Binary _Image;
		
		private string _ImagePath;
		
		public EcoregionListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEcoregion", DbType="Int NOT NULL")]
		public int IdEcoregion
		{
			get
			{
				return this._IdEcoregion;
			}
			set
			{
				if ((this._IdEcoregion != value))
				{
					this._IdEcoregion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(50)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this._Image = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImagePath", DbType="VarChar(150)")]
		public string ImagePath
		{
			get
			{
				return this._ImagePath;
			}
			set
			{
				if ((this._ImagePath != value))
				{
					this._ImagePath = value;
				}
			}
		}
	}
	
	public partial class EcoRegionPlantListResult
	{
		
		private int _IdEcoregion;
		
		private string _Name;
		
		private string _Description;
		
		private System.Data.Linq.Binary _Image;
		
		private string _ImagePath;
		
		public EcoRegionPlantListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEcoregion", DbType="Int NOT NULL")]
		public int IdEcoregion
		{
			get
			{
				return this._IdEcoregion;
			}
			set
			{
				if ((this._IdEcoregion != value))
				{
					this._IdEcoregion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(50)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this._Image = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImagePath", DbType="VarChar(150)")]
		public string ImagePath
		{
			get
			{
				return this._ImagePath;
			}
			set
			{
				if ((this._ImagePath != value))
				{
					this._ImagePath = value;
				}
			}
		}
	}
	
	public partial class PhotoGetResult
	{
		
		private int _IdPhoto;
		
		private int _IdPlant;
		
		private string _Type;
		
		private string _Name;
		
		private System.Data.Linq.Binary _Data;
		
		private string _Path;
		
		public PhotoGetResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPhoto", DbType="Int NOT NULL")]
		public int IdPhoto
		{
			get
			{
				return this._IdPhoto;
			}
			set
			{
				if ((this._IdPhoto != value))
				{
					this._IdPhoto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPlant", DbType="Int NOT NULL")]
		public int IdPlant
		{
			get
			{
				return this._IdPlant;
			}
			set
			{
				if ((this._IdPlant != value))
				{
					this._IdPlant = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(250)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(250)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this._Data = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Path", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Path
		{
			get
			{
				return this._Path;
			}
			set
			{
				if ((this._Path != value))
				{
					this._Path = value;
				}
			}
		}
	}
	
	public partial class PhotoListResult
	{
		
		private int _IdPhoto;
		
		private int _IdPlant;
		
		private string _Type;
		
		private string _Name;
		
		private System.Data.Linq.Binary _Data;
		
		private string _Path;
		
		public PhotoListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPhoto", DbType="Int NOT NULL")]
		public int IdPhoto
		{
			get
			{
				return this._IdPhoto;
			}
			set
			{
				if ((this._IdPhoto != value))
				{
					this._IdPhoto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPlant", DbType="Int NOT NULL")]
		public int IdPlant
		{
			get
			{
				return this._IdPlant;
			}
			set
			{
				if ((this._IdPlant != value))
				{
					this._IdPlant = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(250)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(250)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this._Data = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Path", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Path
		{
			get
			{
				return this._Path;
			}
			set
			{
				if ((this._Path != value))
				{
					this._Path = value;
				}
			}
		}
	}
	
	public partial class PlantDepartmentListResult
	{
		
		private int _IdPlant;
		
		private int _IdUser;
		
		private System.Nullable<int> _Status;
		
		private System.Nullable<int> _CountSearchs;
		
		private string _CommonName;
		
		private string _ScientificName;
		
		private string _Family;
		
		private string _Characteristics;
		
		private string _Distributions;
		
		private string _Uses;
		
		private System.Nullable<System.DateTime> _CreationDate;
		
		private System.Nullable<System.DateTime> _UptoDate;
		
		private string _Type;
		
		private string _Morphology;
		
		private string _Color;
		
		private string _Test;
		
		public PlantDepartmentListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPlant", DbType="Int NOT NULL")]
		public int IdPlant
		{
			get
			{
				return this._IdPlant;
			}
			set
			{
				if ((this._IdPlant != value))
				{
					this._IdPlant = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUser", DbType="Int NOT NULL")]
		public int IdUser
		{
			get
			{
				return this._IdUser;
			}
			set
			{
				if ((this._IdUser != value))
				{
					this._IdUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountSearchs", DbType="Int")]
		public System.Nullable<int> CountSearchs
		{
			get
			{
				return this._CountSearchs;
			}
			set
			{
				if ((this._CountSearchs != value))
				{
					this._CountSearchs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommonName", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string CommonName
		{
			get
			{
				return this._CommonName;
			}
			set
			{
				if ((this._CommonName != value))
				{
					this._CommonName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScientificName", DbType="VarChar(250)")]
		public string ScientificName
		{
			get
			{
				return this._ScientificName;
			}
			set
			{
				if ((this._ScientificName != value))
				{
					this._ScientificName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Family", DbType="VarChar(250)")]
		public string Family
		{
			get
			{
				return this._Family;
			}
			set
			{
				if ((this._Family != value))
				{
					this._Family = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Characteristics", DbType="VarChar(250)")]
		public string Characteristics
		{
			get
			{
				return this._Characteristics;
			}
			set
			{
				if ((this._Characteristics != value))
				{
					this._Characteristics = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Distributions", DbType="VarChar(250)")]
		public string Distributions
		{
			get
			{
				return this._Distributions;
			}
			set
			{
				if ((this._Distributions != value))
				{
					this._Distributions = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uses", DbType="VarChar(250)")]
		public string Uses
		{
			get
			{
				return this._Uses;
			}
			set
			{
				if ((this._Uses != value))
				{
					this._Uses = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationDate", DbType="Date")]
		public System.Nullable<System.DateTime> CreationDate
		{
			get
			{
				return this._CreationDate;
			}
			set
			{
				if ((this._CreationDate != value))
				{
					this._CreationDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UptoDate", DbType="Date")]
		public System.Nullable<System.DateTime> UptoDate
		{
			get
			{
				return this._UptoDate;
			}
			set
			{
				if ((this._UptoDate != value))
				{
					this._UptoDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(250)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Morphology", DbType="VarChar(250)")]
		public string Morphology
		{
			get
			{
				return this._Morphology;
			}
			set
			{
				if ((this._Morphology != value))
				{
					this._Morphology = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="VarChar(250)")]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this._Color = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Test", DbType="NChar(10)")]
		public string Test
		{
			get
			{
				return this._Test;
			}
			set
			{
				if ((this._Test != value))
				{
					this._Test = value;
				}
			}
		}
	}
	
	public partial class PlantEcoRegionListResult
	{
		
		private int _IdPlant;
		
		private int _IdUser;
		
		private System.Nullable<int> _Status;
		
		private System.Nullable<int> _CountSearchs;
		
		private string _CommonName;
		
		private string _ScientificName;
		
		private string _Family;
		
		private string _Characteristics;
		
		private string _Distributions;
		
		private string _Uses;
		
		private System.Nullable<System.DateTime> _CreationDate;
		
		private System.Nullable<System.DateTime> _UptoDate;
		
		private string _Type;
		
		private string _Morphology;
		
		private string _Color;
		
		private string _Test;
		
		public PlantEcoRegionListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPlant", DbType="Int NOT NULL")]
		public int IdPlant
		{
			get
			{
				return this._IdPlant;
			}
			set
			{
				if ((this._IdPlant != value))
				{
					this._IdPlant = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUser", DbType="Int NOT NULL")]
		public int IdUser
		{
			get
			{
				return this._IdUser;
			}
			set
			{
				if ((this._IdUser != value))
				{
					this._IdUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountSearchs", DbType="Int")]
		public System.Nullable<int> CountSearchs
		{
			get
			{
				return this._CountSearchs;
			}
			set
			{
				if ((this._CountSearchs != value))
				{
					this._CountSearchs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommonName", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string CommonName
		{
			get
			{
				return this._CommonName;
			}
			set
			{
				if ((this._CommonName != value))
				{
					this._CommonName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScientificName", DbType="VarChar(250)")]
		public string ScientificName
		{
			get
			{
				return this._ScientificName;
			}
			set
			{
				if ((this._ScientificName != value))
				{
					this._ScientificName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Family", DbType="VarChar(250)")]
		public string Family
		{
			get
			{
				return this._Family;
			}
			set
			{
				if ((this._Family != value))
				{
					this._Family = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Characteristics", DbType="VarChar(250)")]
		public string Characteristics
		{
			get
			{
				return this._Characteristics;
			}
			set
			{
				if ((this._Characteristics != value))
				{
					this._Characteristics = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Distributions", DbType="VarChar(250)")]
		public string Distributions
		{
			get
			{
				return this._Distributions;
			}
			set
			{
				if ((this._Distributions != value))
				{
					this._Distributions = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uses", DbType="VarChar(250)")]
		public string Uses
		{
			get
			{
				return this._Uses;
			}
			set
			{
				if ((this._Uses != value))
				{
					this._Uses = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationDate", DbType="Date")]
		public System.Nullable<System.DateTime> CreationDate
		{
			get
			{
				return this._CreationDate;
			}
			set
			{
				if ((this._CreationDate != value))
				{
					this._CreationDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UptoDate", DbType="Date")]
		public System.Nullable<System.DateTime> UptoDate
		{
			get
			{
				return this._UptoDate;
			}
			set
			{
				if ((this._UptoDate != value))
				{
					this._UptoDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(250)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Morphology", DbType="VarChar(250)")]
		public string Morphology
		{
			get
			{
				return this._Morphology;
			}
			set
			{
				if ((this._Morphology != value))
				{
					this._Morphology = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="VarChar(250)")]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this._Color = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Test", DbType="NChar(10)")]
		public string Test
		{
			get
			{
				return this._Test;
			}
			set
			{
				if ((this._Test != value))
				{
					this._Test = value;
				}
			}
		}
	}
	
	public partial class PlantListResult
	{
		
		private int _IdPlant;
		
		private int _IdUser;
		
		private System.Nullable<int> _Status;
		
		private System.Nullable<int> _CountSearchs;
		
		private string _CommonName;
		
		private string _ScientificName;
		
		private string _Family;
		
		private string _Characteristics;
		
		private string _Distributions;
		
		private string _Uses;
		
		private System.Nullable<System.DateTime> _CreationDate;
		
		private System.Nullable<System.DateTime> _UptoDate;
		
		private string _Type;
		
		private string _Morphology;
		
		private string _Color;
		
		private string _Test;
		
		public PlantListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPlant", DbType="Int NOT NULL")]
		public int IdPlant
		{
			get
			{
				return this._IdPlant;
			}
			set
			{
				if ((this._IdPlant != value))
				{
					this._IdPlant = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUser", DbType="Int NOT NULL")]
		public int IdUser
		{
			get
			{
				return this._IdUser;
			}
			set
			{
				if ((this._IdUser != value))
				{
					this._IdUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountSearchs", DbType="Int")]
		public System.Nullable<int> CountSearchs
		{
			get
			{
				return this._CountSearchs;
			}
			set
			{
				if ((this._CountSearchs != value))
				{
					this._CountSearchs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommonName", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string CommonName
		{
			get
			{
				return this._CommonName;
			}
			set
			{
				if ((this._CommonName != value))
				{
					this._CommonName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScientificName", DbType="VarChar(250)")]
		public string ScientificName
		{
			get
			{
				return this._ScientificName;
			}
			set
			{
				if ((this._ScientificName != value))
				{
					this._ScientificName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Family", DbType="VarChar(250)")]
		public string Family
		{
			get
			{
				return this._Family;
			}
			set
			{
				if ((this._Family != value))
				{
					this._Family = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Characteristics", DbType="VarChar(250)")]
		public string Characteristics
		{
			get
			{
				return this._Characteristics;
			}
			set
			{
				if ((this._Characteristics != value))
				{
					this._Characteristics = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Distributions", DbType="VarChar(250)")]
		public string Distributions
		{
			get
			{
				return this._Distributions;
			}
			set
			{
				if ((this._Distributions != value))
				{
					this._Distributions = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uses", DbType="VarChar(250)")]
		public string Uses
		{
			get
			{
				return this._Uses;
			}
			set
			{
				if ((this._Uses != value))
				{
					this._Uses = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationDate", DbType="Date")]
		public System.Nullable<System.DateTime> CreationDate
		{
			get
			{
				return this._CreationDate;
			}
			set
			{
				if ((this._CreationDate != value))
				{
					this._CreationDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UptoDate", DbType="Date")]
		public System.Nullable<System.DateTime> UptoDate
		{
			get
			{
				return this._UptoDate;
			}
			set
			{
				if ((this._UptoDate != value))
				{
					this._UptoDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(250)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Morphology", DbType="VarChar(250)")]
		public string Morphology
		{
			get
			{
				return this._Morphology;
			}
			set
			{
				if ((this._Morphology != value))
				{
					this._Morphology = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="VarChar(250)")]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this._Color = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Test", DbType="NChar(10)")]
		public string Test
		{
			get
			{
				return this._Test;
			}
			set
			{
				if ((this._Test != value))
				{
					this._Test = value;
				}
			}
		}
	}
	
	public partial class UserFavoriteListResult
	{
		
		private int _IdPlant;
		
		private int _IdUser;
		
		private System.Nullable<int> _Status;
		
		private System.Nullable<int> _CountSearchs;
		
		private string _CommonName;
		
		private string _ScientificName;
		
		private string _Family;
		
		private string _Characteristics;
		
		private string _Distributions;
		
		private string _Uses;
		
		private System.Nullable<System.DateTime> _CreationDate;
		
		private System.Nullable<System.DateTime> _UptoDate;
		
		private string _Type;
		
		private string _Morphology;
		
		private string _Color;
		
		private string _Test;
		
		public UserFavoriteListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPlant", DbType="Int NOT NULL")]
		public int IdPlant
		{
			get
			{
				return this._IdPlant;
			}
			set
			{
				if ((this._IdPlant != value))
				{
					this._IdPlant = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUser", DbType="Int NOT NULL")]
		public int IdUser
		{
			get
			{
				return this._IdUser;
			}
			set
			{
				if ((this._IdUser != value))
				{
					this._IdUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountSearchs", DbType="Int")]
		public System.Nullable<int> CountSearchs
		{
			get
			{
				return this._CountSearchs;
			}
			set
			{
				if ((this._CountSearchs != value))
				{
					this._CountSearchs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommonName", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string CommonName
		{
			get
			{
				return this._CommonName;
			}
			set
			{
				if ((this._CommonName != value))
				{
					this._CommonName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScientificName", DbType="VarChar(250)")]
		public string ScientificName
		{
			get
			{
				return this._ScientificName;
			}
			set
			{
				if ((this._ScientificName != value))
				{
					this._ScientificName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Family", DbType="VarChar(250)")]
		public string Family
		{
			get
			{
				return this._Family;
			}
			set
			{
				if ((this._Family != value))
				{
					this._Family = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Characteristics", DbType="VarChar(250)")]
		public string Characteristics
		{
			get
			{
				return this._Characteristics;
			}
			set
			{
				if ((this._Characteristics != value))
				{
					this._Characteristics = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Distributions", DbType="VarChar(250)")]
		public string Distributions
		{
			get
			{
				return this._Distributions;
			}
			set
			{
				if ((this._Distributions != value))
				{
					this._Distributions = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uses", DbType="VarChar(250)")]
		public string Uses
		{
			get
			{
				return this._Uses;
			}
			set
			{
				if ((this._Uses != value))
				{
					this._Uses = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationDate", DbType="Date")]
		public System.Nullable<System.DateTime> CreationDate
		{
			get
			{
				return this._CreationDate;
			}
			set
			{
				if ((this._CreationDate != value))
				{
					this._CreationDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UptoDate", DbType="Date")]
		public System.Nullable<System.DateTime> UptoDate
		{
			get
			{
				return this._UptoDate;
			}
			set
			{
				if ((this._UptoDate != value))
				{
					this._UptoDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(250)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Morphology", DbType="VarChar(250)")]
		public string Morphology
		{
			get
			{
				return this._Morphology;
			}
			set
			{
				if ((this._Morphology != value))
				{
					this._Morphology = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="VarChar(250)")]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this._Color = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Test", DbType="NChar(10)")]
		public string Test
		{
			get
			{
				return this._Test;
			}
			set
			{
				if ((this._Test != value))
				{
					this._Test = value;
				}
			}
		}
	}
	
	public partial class UserGetResult
	{
		
		private int _IdUser;
		
		private string _UserName;
		
		private string _Password;
		
		private string _Email;
		
		private short _Active;
		
		private short _AppMember;
		
		private string _Name;
		
		private string _SurName;
		
		public UserGetResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUser", DbType="Int NOT NULL")]
		public int IdUser
		{
			get
			{
				return this._IdUser;
			}
			set
			{
				if ((this._IdUser != value))
				{
					this._IdUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="SmallInt NOT NULL")]
		public short Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppMember", DbType="SmallInt NOT NULL")]
		public short AppMember
		{
			get
			{
				return this._AppMember;
			}
			set
			{
				if ((this._AppMember != value))
				{
					this._AppMember = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(250)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SurName", DbType="VarChar(250)")]
		public string SurName
		{
			get
			{
				return this._SurName;
			}
			set
			{
				if ((this._SurName != value))
				{
					this._SurName = value;
				}
			}
		}
	}
	
	public partial class PlantGetResult
	{
		
		private int _IdPlant;
		
		private int _IdUser;
		
		private System.Nullable<int> _Status;
		
		private System.Nullable<int> _CountSearchs;
		
		private string _CommonName;
		
		private string _ScientificName;
		
		private string _Family;
		
		private string _Characteristics;
		
		private string _Distributions;
		
		private string _Uses;
		
		private System.Nullable<System.DateTime> _CreationDate;
		
		private System.Nullable<System.DateTime> _UptoDate;
		
		private string _Type;
		
		private string _Morphology;
		
		private string _Color;
		
		private string _Test;
		
		public PlantGetResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPlant", DbType="Int NOT NULL")]
		public int IdPlant
		{
			get
			{
				return this._IdPlant;
			}
			set
			{
				if ((this._IdPlant != value))
				{
					this._IdPlant = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUser", DbType="Int NOT NULL")]
		public int IdUser
		{
			get
			{
				return this._IdUser;
			}
			set
			{
				if ((this._IdUser != value))
				{
					this._IdUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountSearchs", DbType="Int")]
		public System.Nullable<int> CountSearchs
		{
			get
			{
				return this._CountSearchs;
			}
			set
			{
				if ((this._CountSearchs != value))
				{
					this._CountSearchs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommonName", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string CommonName
		{
			get
			{
				return this._CommonName;
			}
			set
			{
				if ((this._CommonName != value))
				{
					this._CommonName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScientificName", DbType="VarChar(250)")]
		public string ScientificName
		{
			get
			{
				return this._ScientificName;
			}
			set
			{
				if ((this._ScientificName != value))
				{
					this._ScientificName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Family", DbType="VarChar(250)")]
		public string Family
		{
			get
			{
				return this._Family;
			}
			set
			{
				if ((this._Family != value))
				{
					this._Family = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Characteristics", DbType="VarChar(250)")]
		public string Characteristics
		{
			get
			{
				return this._Characteristics;
			}
			set
			{
				if ((this._Characteristics != value))
				{
					this._Characteristics = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Distributions", DbType="VarChar(250)")]
		public string Distributions
		{
			get
			{
				return this._Distributions;
			}
			set
			{
				if ((this._Distributions != value))
				{
					this._Distributions = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uses", DbType="VarChar(250)")]
		public string Uses
		{
			get
			{
				return this._Uses;
			}
			set
			{
				if ((this._Uses != value))
				{
					this._Uses = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationDate", DbType="Date")]
		public System.Nullable<System.DateTime> CreationDate
		{
			get
			{
				return this._CreationDate;
			}
			set
			{
				if ((this._CreationDate != value))
				{
					this._CreationDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UptoDate", DbType="Date")]
		public System.Nullable<System.DateTime> UptoDate
		{
			get
			{
				return this._UptoDate;
			}
			set
			{
				if ((this._UptoDate != value))
				{
					this._UptoDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(250)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Morphology", DbType="VarChar(250)")]
		public string Morphology
		{
			get
			{
				return this._Morphology;
			}
			set
			{
				if ((this._Morphology != value))
				{
					this._Morphology = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="VarChar(250)")]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this._Color = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Test", DbType="NChar(10)")]
		public string Test
		{
			get
			{
				return this._Test;
			}
			set
			{
				if ((this._Test != value))
				{
					this._Test = value;
				}
			}
		}
	}
	
	public partial class PlantUserListResult
	{
		
		private int _IdPlant;
		
		private int _IdUser;
		
		private System.Nullable<int> _Status;
		
		private System.Nullable<int> _CountSearchs;
		
		private string _CommonName;
		
		private string _ScientificName;
		
		private string _Family;
		
		private string _Characteristics;
		
		private string _Distributions;
		
		private string _Uses;
		
		private System.Nullable<System.DateTime> _CreationDate;
		
		private System.Nullable<System.DateTime> _UptoDate;
		
		private string _Type;
		
		private string _Morphology;
		
		private string _Color;
		
		private string _Test;
		
		public PlantUserListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPlant", DbType="Int NOT NULL")]
		public int IdPlant
		{
			get
			{
				return this._IdPlant;
			}
			set
			{
				if ((this._IdPlant != value))
				{
					this._IdPlant = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUser", DbType="Int NOT NULL")]
		public int IdUser
		{
			get
			{
				return this._IdUser;
			}
			set
			{
				if ((this._IdUser != value))
				{
					this._IdUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountSearchs", DbType="Int")]
		public System.Nullable<int> CountSearchs
		{
			get
			{
				return this._CountSearchs;
			}
			set
			{
				if ((this._CountSearchs != value))
				{
					this._CountSearchs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommonName", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string CommonName
		{
			get
			{
				return this._CommonName;
			}
			set
			{
				if ((this._CommonName != value))
				{
					this._CommonName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScientificName", DbType="VarChar(250)")]
		public string ScientificName
		{
			get
			{
				return this._ScientificName;
			}
			set
			{
				if ((this._ScientificName != value))
				{
					this._ScientificName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Family", DbType="VarChar(250)")]
		public string Family
		{
			get
			{
				return this._Family;
			}
			set
			{
				if ((this._Family != value))
				{
					this._Family = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Characteristics", DbType="VarChar(250)")]
		public string Characteristics
		{
			get
			{
				return this._Characteristics;
			}
			set
			{
				if ((this._Characteristics != value))
				{
					this._Characteristics = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Distributions", DbType="VarChar(250)")]
		public string Distributions
		{
			get
			{
				return this._Distributions;
			}
			set
			{
				if ((this._Distributions != value))
				{
					this._Distributions = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uses", DbType="VarChar(250)")]
		public string Uses
		{
			get
			{
				return this._Uses;
			}
			set
			{
				if ((this._Uses != value))
				{
					this._Uses = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationDate", DbType="Date")]
		public System.Nullable<System.DateTime> CreationDate
		{
			get
			{
				return this._CreationDate;
			}
			set
			{
				if ((this._CreationDate != value))
				{
					this._CreationDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UptoDate", DbType="Date")]
		public System.Nullable<System.DateTime> UptoDate
		{
			get
			{
				return this._UptoDate;
			}
			set
			{
				if ((this._UptoDate != value))
				{
					this._UptoDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(250)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Morphology", DbType="VarChar(250)")]
		public string Morphology
		{
			get
			{
				return this._Morphology;
			}
			set
			{
				if ((this._Morphology != value))
				{
					this._Morphology = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="VarChar(250)")]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this._Color = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Test", DbType="NChar(10)")]
		public string Test
		{
			get
			{
				return this._Test;
			}
			set
			{
				if ((this._Test != value))
				{
					this._Test = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
